homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('experience/', views.skills, name='skills'),
    path('hobby/', views.hobby, name='hobby'),
    path('contact/', views.contact, name='contact'),
    path('music/', views.music, name='music'),
    path('schedule/', views.schedule_create, name="schedule"),
    path('delete/<id>/', views.schedule_delete, name="schedule_delete")
]

ppw/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models
import django.utils.timezone


# Create your models here.
class Schedule1(models.Model):

    title = models.CharField(max_length=100)
    place = models.CharField(max_length=100, null=True)
    category = models.CharField(
        max_length=8
    )
   
    date = models.DateField(auto_now_add = False, default = django.utils.timezone.now)
    day = models.CharField(max_length=10, default=None, null=True)
    time = models.TimeField(auto_now_add = False, default = django.utils.timezone.now)

    description = models.CharField(max_length=100, default = "")

    def __str__(self):
        return self.title

homepage/forms.py
from django import forms
from . import models
from django.utils import timezone
from datetime import datetime

class Time(forms.TimeInput):
    input_type = "time"

class Date(forms.DateInput):
    input_type = "date"
    input_formats = ['%d %b %Y']


class Schedule(forms.ModelForm):
    class Meta:
        model = models.Schedule1
        fields = ['title', 'place', 'category', 'date', 'time', 'description']

        widgets = {
            "time": Time,
            "date": Date
        }

homepage/views.py
from django.shortcuts import render, redirect
from . import forms
from .models import Schedule1


# Create your views here.
def home(request):
	return render(request, "ppwHome1.html")

def about(request):
	return render(request, "ppwAbout.html")

def skills(request):
	return render(request, "ppwSkills.html")

def hobby(request):
	return render(request, "ppwHobby.html")

def contact(request):
	return render(request, "ppwContact.html")

def music(request):
	return render(request, "ppwMusic.html")

# Create your views here.

def schedule_create(request):
    if request.method == "POST":
        form = forms.Schedule(request.POST)

        if form.is_valid():   
            new_sched = form.save(commit=False)
            new_sched.day = new_sched.date.strftime("%A")
            new_sched.save()
        
        return redirect("homepage:schedule")
    else:
        form = forms.Schedule()
        return render(request, "schedule.html", {"form" : form, "schedules": Schedule1.objects.all().order_by("date")})

def schedule_delete(request, id):
    jadwal = Schedule1.objects.get(id=id)
    jadwal.delete()
    return redirect("homepage:schedule")

homepage/templates/navbar.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel = "stylesheet" href = "{% static 'css/ppw.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Inconsolata&display=swap" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>FadhilP</title>
</head>
<body>
   <nav class="navbar navbar-expand-md navbar-light bg-dark">

        <button class="navbar-toggler" data-toggle="collapse" data-target="#collapse-target">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="collapse-target">
            <ul class="navbar-nav">
                <li class="nav-item">
                <a class="nav-link" href="{% url 'homepage:home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'homepage:about' %}">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'homepage:skills' %}">Skills</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'homepage:hobby' %}">Hobby</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'homepage:contact' %}">Contact</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'homepage:music' %}">Arranging</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'homepage:schedule' %}">Schedule</a>
                </li>
            </ul>
        </div>
   </nav>
    {% block content %}
    {% endblock %}
</body>
</html>

homepage/templates/ppwAbout.html
<!DOCTYPE html>
{% extends 'navbar.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel = "stylesheet" href = "{% static 'css/ppw.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Inconsolata&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>About FadhilP</title>
</head>
<body>
    {% block content %}
    <div class="container-fluid">
        <div id="about" class="row section">
            <div class="col-md-6 offset-md-3">
                <h3 class="mt-4 section-title">About Me</h3>
                <hr class="hr" />
                <img id="profile" src="{% static 'images/pp.png' %}">
                <div class="about-detail">
                    <p>
                        My name is Fadhil Pradipta Widyanto. I'm an undergraduate student majoring in computer science at
                        Universitas Indonesia. I spend my free time on playing or making original transcriptions on piano.
                    </p>
                    <p>
                        Date of Birth:<br/>
                        26th of June 2000, <br/> Jakarta
                    </p>
                    <p>
                        Currently Studying at:<br/>
                        Universitas Indonesia - <br/>
                        Computer Science
                    </p>
                </div>
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </div>
    {% endblock %}
</body>
</html>

homepage/templates/ppwContact.html
<!DOCTYPE html>
{% extends 'navbar.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel = "stylesheet" href = "{% static 'css/ppw.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Inconsolata&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>FadhilP</title>
</head>
<body>
    {% block content %}
    <div class="container-fluid">
        <div id="contact" class ="row section">
            <div class="col-md-6 offset-md-3">
                <h3 class="mt-3 section-title">Contact Me</h3>
                <hr class="hr"/>
            </div>
        </div>
        <div class="row section">
            <div class="col-md-2 offset-md-4 my-auto">
                <img class="logo-s" src="{% static 'images/email_icon.png' %}">
            </div>
            <div class="col-md-2 my-auto">
                <p>fadhilpradipta0@gmail.com</p>
            </div>
        </div>
        <div class="row section">
            <div class="col-md-2 offset-md-4 my-auto">
                <img class="logo-s" src="{% static 'images/line_icon.png' %}">
            </div>
            <div class="col-md-2 my-auto">
                <p>fadhilpradiptaw</p>
            </div>
        </div>
        <div class="row section">
            <div class="col-md-2 offset-md-4 my-auto">
                <img class="logo-s" src="{% static 'images/phone_icon.png' %}">
            </div>
            <div class="col-md-2 my-auto">
                <p>081288383554</p>
            </div>
        </div>

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </div>
    {% endblock %}
</body>
</html>

homepage/templates/ppwHobby.html
<!DOCTYPE html>
{% extends 'navbar.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel = "stylesheet" href = "{% static 'css/ppw.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Inconsolata&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>FadhilP</title>
</head>
<body>
    {% block content %}
    <div class="container-fluid">
        <div id="hobby" class="row section text-white">
            <div class="col-md-6 offset-md-3">
                <h3 class="mt-5 section-title">Hobby</h3>
                <hr id="white" class="hr"/>
            </div>
            <div class="col-md-10 offset-md-1">
                <p>I play piano and arrange/transcribe pieces on my free time. <a href="ppwMusic.html">Find out how.</a></p>
                <p>Here are some arrangements and transcriptions that I made in the past 3 months:</p>
            </div>
            <div class="col-md-10 offset-md-1">
                <p>1. Pelican Wish composed by Kana</p>
                <audio controls>
                    <source src="audio/A_Pelican_Wish.mp3" type="audio/mp3">
                </audio>
            </div>
            <div class="col-md-10 offset-md-1">
                <p>2. Unnamed Improvisation by Shadow</p>
                <audio controls>
                    <source src="audio/Shadow's Improv(modified).mp3" type="audio/mp3">
                </audio>
            </div>
        </div>

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </div>
    {% endblock %}
</body>
</html>

homepage/templates/ppwHome1.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel = "stylesheet" href = "{% static 'css/ppw.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Inconsolata&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>FadhilP</title>
</head>
<body>
    <div class="bear-bg"></div>
    <div class="container-fluid">
        <div class="row header-section">
            <div class="col-md-4 my-auto">
                <h1 class="ml-5">Hello World, I'm Fadhil</h1>
            </div>
            <div class="col-md-5 my-auto">
                <a id="about_link" href="{% url 'homepage:about' %}"><h3 class="mb-5 ml-5">About_me</h3></a>
                <a id="exp_link" href="{% url 'homepage:skills' %}"><h3 class="mb-5 ml-5">Experience_and_skills</h3></a>
                <a id="hobby_link" href="{% url 'homepage:hobby' %}"><h3 class="mb-5 ml-5">Hobby</h3></a>
                <a id="contact_link" href="{% url 'homepage:contact' %}"><h3 class="mb-5 ml-5">Contact_me</h3></a>
                <a href="{% url 'homepage:music' %}"><h3 class="mb-5 ml-5">How I Arrange</h3></a>
                <a href="{% url 'homepage:schedule' %}"><h3 class="mb-5 ml-5">Schedule</h3></a>
            </div>
        </div>

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </div>
</body>
</html>

homepage/templates/ppwMusic.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel = "stylesheet" href = "{% static 'css/ppw.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Inconsolata&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>FadhilP-Music</title>
</head>
<body>
    <div class=black-bg></div>
    <div class="page2-bg"></div>
    <div class="container-fluid">
        <div class="row header-section">
            <div class="col-md-4 my-auto">
                <h1 class="ml-5">How I Arrange</h1>
            </div>
            <div class="col-md-3 my-auto">
                <a id="home_link" href="{% url 'homepage:home' %}"><h3 class="mb-5 ml-5">Home</h3></a>
                <a id="sw_link" href="#sw"><h3 class="mb-5 ml-5">Software</h3></a>
                <a id="ins_link" href="#ins"><h3 class="mb-5 ml-5">Inspiration</h3></a>
                <a id="style_link" href="#style"><h3 class="mb-5 ml-5">Style</h3></a>
            </div>
        </div>
        <div id="sw" class="row section">
            <div class="col-md-6 offset-md-3 my-auto text-center">
                <h3 class="mt-5 section-title">Software</h3>
                <hr class="hr" />
                <a href="https://musescore.org/en/download" target="_blank"><img class="logo-c mt-5" src="{% static 'images/musescore_logo.png' %}"></a>
                <div class="about-detail">
                    <p>I use Musescore 3 to make the sheets of my arrangements</p>
                </div>
            </div>
        </div>
        <div id="ins" class="row section">
            <div class="col-md-6 offset-md-3">
                <h3 class="mt-5 section-title">Inspirations</h3>
                <hr class="hr mb-5" />
            </div>
            <div class="col-md-3 offset-md-1 text-center">
                <a href="https://www.youtube.com/user/Animenzzz" target="_blank"><img class="logo-c mt-5 mb-5" src="{% static 'images/animenz.jpeg' %}"></a>
            </div>
            <div class="col-md-4 text-center">
                <a href="https://www.youtube.com/channel/UCSqAgjHIy36gnSTBvG3tltw" target="_blank"><img class="logo-c mt-5 mb-5" src="{% static 'images/james-chou.jpg' %}"></a>
            </div>
            <div class="col-md-3 text-center">
                <a href="https://www.youtube.com/channel/UCXbCo1dYKNceoxUC7rKMjZw" target="_blank"><img class="logo-c mt-5 mb-5" src="{% static 'images/zzz.jpg' %}"></a>
            </div>
        </div>
        <div id="style" class="row section">
            <div class="col-md-8 offset-md-2">
                <h3 class="mt-5 section-title">Style</h3>
                <hr class="hr" />
                <div class="about-detail text-center">
                    <p>
                        I will use my most recent arrangement, Pelican Wish composed by Kana as a reference
                    </p>
                    <img class="music-ex mt-5" src="{% static 'images/note-ex1.png' %}">
                    <p>
                        I usually opened up with something slow, even though the original<br/>
                        doesn’t. I like to use a span of 10th or more for the left hand because<br/>
                        it creates a dreamy feel like you’re going to start on a journey<br/>
                    </p>
                    <img class="music-ex mt-5" src="{% static 'images/note-ex2.png' %}">
                    <p>
                        On the verse, I use a lot of polyphony. James Chou and zzz use a lot of these and<br/>
                        I’m still learning on how to do it properly. For the 1st verse I only use polyphony on the<br/>
                        2nd section, usually with 3 voices while on the 2nd verse I use up to 4 voices.<br/>
                    </p>
                    <img class="music-ex ml-auto mt-5" src="{% static 'images/note-ex3.png' %}">
                    <p>
                        On the chorus, I use simple but grandoise chords to accompany the melody.<br/>
                        I usually use octaves or 4 block chords for the melody.<br/>
                    </p>
                </div>
            </div>
        </div>
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <script type="text/javascript">
            $(document).ready(function() {
                $('#sw_link').click(function(e) {
                    e.preventDefault();

                    $('html, body').animate({
                    scrollTop: $('#sw').offset().top
                    }, 500);
                });
                $('#ins_link').click(function(e) {
                    e.preventDefault();

                    $('html, body').animate({
                    scrollTop: $('#ins').offset().top
                    }, 500);
                });
                $('#style_link').click(function(e) {
                    e.preventDefault();

                    $('html, body').animate({
                    scrollTop: $('#style').offset().top
                    }, 500);
                });
            });
        </script>
    </div>
</body>
</html>

homepage/templates/schedule.html
<!DOCTYPE html>
{% extends 'navbar.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel = "stylesheet" href = "{% static 'css/ppw.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Inconsolata&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Jadwal</title>
</head>
<body>
    {% block content %}
    <div class="jadwal-section">
        <form class="site-form" action="" method="post">
            {% csrf_token %}
            <p>Title: {{ form.title }} </p>
            <!-- {{ form.date_time }} -->
            <p>Place: {{ form.place }}</p>
            <p>Category: {{ form.category }}</p>
            <p>Date: {{ form.date }}</p>
            <p>Time: {{ form.time }}</p>
            <p>Description: {{ form.description }}</p>
            <input class="butt" type="submit" value="Add"/>
        </form>
        <div class="semua-jadwal">
            {% for schedule in schedules %}
            <div class="jadwal">
                <div class="info-jadwal">
                    <p>Title: {{ schedule.title }}</p>
                    <p>Place: {{ schedule.place }}</p>
                    <p>Category: {{ schedule.category }}</p>
                    <p>Day: {{ schedule.day }}</p>
                    <p>Date: {{ schedule.date }}</p>
                    <p>Time: {{ schedule.time }}</p>
                    <p>Description: {{ schedule.description }}</p>
                </div>
                <a href="{% url 'homepage:schedule_delete' id=schedule.id %}"><button>Delete</button></a>
            </div>

            {% endfor %}
        </div>
        
    </div>

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </div>
    {% endblock %}
</body>
</html>